### ISSUE TITLE
msrestazure.tools.parse_resource_id doesn't parse resource group resource_id

### ISSUE THREAD

**Issue by logachev** [Azure/msrestazure-for-python#115]
If you pass a resource group id, it returns dictionary with only 'name' key.
/subscriptions/guid/resourceGroups/<rg_name>

**Comment by lmazuel** [comment]
@williexu ?

**Comment by williexu** [comment]
The current parsing tool makes the assumption that any ID it is parsing is a ARM resource, which all generally have a part of the id containing `/providers/<resource namespace>`.

As a resource group is not technically an ARM resource, it does not contain this part in its id, and the parsing fails.
That being said, I can add functionality so that a resource group id will be successfully parsed of its group name and subscription id.
