### ISSUE TITLE
MSIauthentication returns underscore_separated keys in token data, unlike adal.

### ISSUE THREAD

**Issue by williexu** [Azure/msrestazure-for-python#116]
Adal serializes the payload from a token request from under_scored to camelCased, whereas the MSIAuth in the msrestazure tools does not.

The same serialization present in adal being done for MSI would be ideal for consistency and make it easier for client python tools that use both auth flows.

ex:
```
MSI from msrestazure
{  
   'client_id':'<id>',
   'access_token':'<id>',
   'ext_expires_in':'288000',
   'expires_in':'28799',
   'token_type':'Bearer',
   'resource':'https://storage.azure.com',
   'not_before':'1535478647',
   'expires_on':'1535507747'
}

Adal:
{  
   'tokenType':'Bearer',
   'expiresIn':3600,
   'expiresOn':'2018-08-28 12:37:18.806210',
   'resource':'https://storage.azure.com',
   'accessToken':'',
   'refreshToken':'',
   'userId':'wilx@microsoft.com',
   'isMRRT':True,
   '_clientId':'04b07795-8ddb-461a-bbee-02f9e1bf7b46',
   '_authority':'https://login.microsoftonline.com/<id>'
}
```

**Comment by lmazuel** [comment]
Since day 1 of Autorest for Python, token is represented and showed in msrestazure as snake_case “access_token”. This is the standard used by requests-oauthlib, and as everything related to “requests” it’s automatically the whole Python standard. That’s consistent with PEP8, that defines naming convention for Python.
Also, changing this will be a massive breaking change for customers, since the token dict is publicly available through the API.

Funny thing to hear that msrestazure should be consistent with ADAL, when msrestazure is older than ADAL for Python (at least older than version 0.3.0 completely revamped by Yugang for the CLI two years ago) 😊. Why not make ADAL consistent with msrestazure and the rest of Python? 😝

**Comment by williexu** [comment]
@lmazuel thanks for the info, my only strong opinion is on the lack of consistency between the two.
From what you say, it does seem ideal if Adal could stick with snake_case.

**Comment by lmazuel** [comment]
I love consistency, but the users of msrestazure and ADAL are usually not the same, so they don't have a problem. The CLI has a problem because it uses both.
Also, since msrestazure is using ADAL under the hood, CLI could ease its burden and use only msrestazure.

**Comment by lmazuel** [comment]
See azure-identity now
