### ISSUE TITLE
InteractiveCredentials calls set_token with incorrect number of parameters

### ISSUE THREAD

**Issue by jacwil** [Azure/msrestazure-for-python#15]
I'm getting "TypeError: set_token() takes exactly 2 arguments (1 given)" when [InteractiveCredentials.\_\_init\_\_()](https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_active_directory.py#L465) gets called.

I noticed documentation is exceedingly scarce for how to use this class, specifically the `redirect` parameter. Is this the class that needs to be used for user accounts requiring multi-factor auth?

**Comment by lmazuel** [comment]
Hi @jacwil 

The current recommendation for 2FA authentication is to use [ADAL](https://github.com/AzureAD/azure-activedirectory-library-for-python). Then, you can use the ADAL wrapper to get a valid `Credentials` instance to use in msrestazure (so any Autorest generated package and Azure SDK for Python).

The ADAL wrapper is in msrestazure since version 0.4.5 ([see RTD](http://msrestazure.readthedocs.io/en/latest/msrestazure.html#msrestazure.azure_active_directory.AdalAuthentication)) and there is a more complete example in the [Azure SDK for Python doc](http://azure-sdk-for-python.readthedocs.io/en/latest/quickstart_authentication.html#using-adal).

**Comment by lmazuel** [comment]
InteractiveCredentials is removed in 0.4.11 (https://github.com/Azure/msrestazure-for-python/pull/41)
