### ISSUE TITLE
Hack async polling code causing sql import issues

### ISSUE THREAD

**Issue by jaredmoo** [Azure/msrestazure-for-python#26]
The python polling code at https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_operation.py#L184 is setting the response code to 200 and then calling the import operation deserializer. 

However the import operation doesn't expect to receive 200 so it's throwing an exception at https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-sql/azure/mgmt/sql/operations/databases_operations.py#L285

**Comment by jaredmoo** [comment]
The ClientException is caught at https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_operation.py#L187 , but then the async code sees the 200 ( at https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_operation.py#L447 ) and thinks that the operation is done . 

Since deserialization never succeeded, the logic at https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_operation.py#L460 tries to GET the original request uri, however the import operation is weird and actually doesn't support GET on the URI that you PUT in order to start the operation in the first place.

This is obviously a crazy corner case, so my workaround is to update the operation documentation to allow 200 return code so that this crazy situation doesn't happen.

https://github.com/Azure/azure-rest-api-specs/pull/1263

Please advise if you have any other suggested workaround :)

**Comment by lmazuel** [comment]
Hi @jaredmoo 

This code is a little complicated, because there is a workaround for a Autorest Python bug that the only way to fix is to break compatibility between Autorest and msrestazure :/

First, I think you're right that when this throws line187, I should replace the old status in the "response" object anyway. I didn't notice that.

Could you describe in details the expected call to Import? Something like:
- PUT /import => 201 with `azure-asyncoperation` 

Mostly the polling is changing depending of the headers used to poll, so this is critical information (not in the Swagger unfortunately :/)

Thanks!

**Comment by jaredmoo** [comment]
The test recording is at https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-sql/tests/recordings/test_sql_db_import_export_mgmt.yaml#L1712

So PUT .../extensions/import -> 202 with location header set to .../extensions/import/importExportOperationResults/{id}

GET .../extensions/import/importExportOperationResults/{id} -> 202 with location header, or 201

GET the original URI (.../extensions/import) is unsupported

**Comment by lmazuel** [comment]
@jaredmoo I will do a patch, if you can test it would be great :)

**Comment by jaredmoo** [comment]
Yes I can test.
